# client settings
serverUrl:      //bjorn-cellar:1099/scaitm_server

starcraftStartingTimeout: 10
matchStartingTimeout:     40
matchEndingTimeout:       60

shortcuts:
    $starcraft:      !required  C:\TM\StarCraft\
    $chaoslauncher:  !required  C:\TM\Chaoslauncher\
