# client settings
serverUrl:      //bjorn-cellar:1099/scaitm_server

starcraft:      C:\TM\StarCraft\
chaoslauncher:  C:\TM\Chaoslauncher\

starcraftStartingTimeout: 10
matchStartingTimeout:     40
matchEndingTimeout:       60
