chaoslauncher:  data/chaoslauncher
BWAPI_374:      data/bwapi_374
BWAPI_401B:     data/bwapi_401B
bot_dir:        data/bots/
map_dir:        data/maps/
tm_settings:    data/tm_settings.ini

replays:        replays/

bots:
  - !!common.Bot [Aiur        , Protoss, dll, BWAPI_374]
  - !!common.Bot [Bonjwa      , Terran , dll, BWAPI_374]
# - !!common.Bot [BTHAI       , Terran , dll, BWAPI_374]
# - !!common.Bot [CruzBot     , Protoss, dll, BWAPI_374]
# - !!common.Bot [HITA        , Zerg   , dll, BWAPI_374]
# - !!common.Bot [IceBot      , Terran , dll, BWAPI_374]
# - !!common.Bot [LetaBot     , Terran , dll, BWAPI_374]
# - !!common.Bot [MaasCraft   , Protoss, dll, BWAPI_401B]
# - !!common.Bot [MooseBot    , Protoss, dll, BWAPI_374]
# - !!common.Bot [Nova        , Terran , dll, BWAPI_374]
# - !!common.Bot [NUSBot      , Protoss, dll, BWAPI_374]
# - !!common.Bot [Oritaka     , Terran , dll, BWAPI_374]
# - !!common.Bot [Skynet      , Protoss, dll, BWAPI_374]
# - !!common.Bot [TerranUAB   , Terran , dll, BWAPI_374]
# - !!common.Bot [UAlbertaBot , Protoss, dll, BWAPI_374]
# - !!common.Bot [Xelnaga     , Protoss, dll, BWAPI_374]
# - !!common.Bot [Ximp        , Protoss, dll, BWAPI_374]
# - !!common.Bot [Yarmouk     , Terran , dll, BWAPI_401B]

maps:
  - !!common.Map aiide/(2)Benzene.scx
# - !!common.Map aiide/(2)Destination.scx
# - !!common.Map aiide/(2)HeartbreakRidge.scx
# - !!common.Map aiide/(3)Aztec.scx
# - !!common.Map aiide/(3)TauCross.scx
# - !!common.Map aiide/(4)Andromeda.scx
# - !!common.Map aiide/(4)CircuitBreaker.scx
# - !!common.Map aiide/(4)EmpireoftheSun.scm
# - !!common.Map aiide/(4)Fortress.scx
# - !!common.Map aiide/(4)Python.scx

# SERVER PORT - Port to listen for clients on
port: 1099

# Games List File - Tournament games to be played
GamesListFile: games.txt

# Results File - Tournament results file
ResultsFile: results.txt

#################################################################
# Auto Generate Detailed Results every 1 minute?
# Syntax - DetailedResults [yes/no]
# Note - Generating detailed results gets very slow for large
#        tournaments, so default is no. You can manually
#        generate the results from the Actions menu in the
#        server, which is recommended
#################################################################
DetailedResults: no

#################################################################
# Clear Existing Results - Clear results on server start?
# Syntax - ClearResultsFile [yes|no|ask]
#################################################################
ClearResults: ask

#################################################################
# Resume Tournament - Resume tournament if results exist?
# Syntax - ClearResultsFile [yes|no|ask]
#################################################################
ResumeTournament: ask
