# server settings
port:           1099
serverUrlPath:  scaitm_server
killClientsOnExit: true
pollPeriod:       0.7

filesToCopyToClientBeforeEachNewMatch:
  - !target [data/newloaderv4.1.exe,  $starcraft/loader.exe]
  - !target [data/tm_settings.ini,    $starcraft/bwapi-data/]

bwapiVersions:
    3.7.4:       !target [data/bwapi_374,    $starcraft/]
    4.0.1-Beta:  !target [data/bwapi_401b,   $starcraft/]
    4.1.0-Beta:  !target [data/bwapi_410b,   $starcraft/]

gameList:    !required  games.yaml
botDir:      !required  data/bots/
mapDir:      !required  data/maps/
replaysDir:  !required  replays/
characterFileMultiplayer:   !required  data/characters/default.mpc
characterFileSingleplayer:  !file      data/characters/default.spc


#################################################################
# Auto Generate Detailed Results every 1 minute?
# Syntax - DetailedResults [yes/no]
# Note - Generating detailed results gets very slow for large
#        tournaments, so default is no. You can manually
#        generate the results from the Actions menu in the
#        server, which is recommended
#################################################################
detailedResults: no

#################################################################
# Clear Existing Results - Clear results on server start?
# Syntax - ClearResultsFile [yes|no|ask]
#################################################################
clearResults: yes

#################################################################
# Resume Tournament - Resume tournament if results exist?
# Syntax - ClearResultsFile [yes|no|ask]
#################################################################
resumeTournament: no
