# server settings
port:           1099
serverUrlPath:  scaitm_server
killClientsOnExit: true

clientFiles:
  - &a             !target [data/chaoslauncher,      $chaoslauncher]
  - &b             !target [data/tm_settings.ini,    $starcraft/bwapi-data/]
  - &bwapi_374     !target [data/bwapi_374,          $starcraft]
  - &bwapi_401b    !target [data/bwapi_401b,         $starcraft]
  - &bwapi_410b    !target [data/bwapi_410b,         $starcraft]

files:
    $bot_dir:    !required  data/bots/
    $map_dir:    !required  data/maps/
    $replays:    !file      replays/
    $games:      !file      games.txt
    $results:    !file      results.txt

bots:
  - !bot [Aiur,                Protoss, dll, [*a, *b, *bwapi_374]]
  - !bot [Bonjwa,              Protoss, dll, [*a, *b, *bwapi_374]]
# - !bot [main-mcts,           Terran , dll, [*a, *b, *bwapi_401b]]
# - !bot [main-attack-closest, Terran , dll, [*a, *b, *bwapi_401b]]
# - !bot [Bonjwa,              Terran , dll, [*a, *b, *bwapi_374]]
# - !bot [BTHAI,               Terran , dll, [*a, *b, *bwapi_374]]
# - !bot [CruzBot,             Protoss, dll, [*a, *b, *bwapi_374]]
# - !bot [HITA,                Zerg   , dll, [*a, *b, *bwapi_374]]
# - !bot [IceBot,              Terran , dll, [*a, *b, *bwapi_374]]
# - !bot [LetaBot,             Terran , dll, [*a, *b, *bwapi_374]]
# - !bot [MaasCraft,           Protoss, dll, [*a, *b, *bwapi_401b]]
# - !bot [MooseBot,            Protoss, dll, [*a, *b, *bwapi_374]]
# - !bot [Nova,                Terran , dll, [*a, *b, *bwapi_374]]
# - !bot [NUSBot,              Protoss, dll, [*a, *b, *bwapi_374]]
# - !bot [Oritaka,             Terran , dll, [*a, *b, *bwapi_374]]
# - !bot [Skynet,              Protoss, dll, [*a, *b, *bwapi_374]]
# - !bot [TerranUAB,           Terran , dll, [*a, *b, *bwapi_374]]
# - !bot [UAlbertaBot,         Protoss, dll, [*a, *b, *bwapi_374]]
# - !bot [Xelnaga,             Protoss, dll, [*a, *b, *bwapi_374]]
# - !bot [Ximp,                Protoss, dll, [*a, *b, *bwapi_374]]
# - !bot [Yarmouk,             Terran , dll, [*a, *b, *bwapi_401b]]

maps:
  - !map aiide/(2)Benzene.scx
# - !map aiide/(2)Destination.scx
# - !map aiide/(2)HeartbreakRidge.scx
# - !map aiide/(3)Aztec.scx
# - !map aiide/(3)TauCross.scx
# - !map aiide/(4)Andromeda.scx
# - !map aiide/(4)CircuitBreaker.scx
# - !map aiide/(4)EmpireoftheSun.scm
# - !map aiide/(4)Fortress.scx
# - !map aiide/(4)Python.scx



#################################################################
# Auto Generate Detailed Results every 1 minute?
# Syntax - DetailedResults [yes/no]
# Note - Generating detailed results gets very slow for large
#        tournaments, so default is no. You can manually
#        generate the results from the Actions menu in the
#        server, which is recommended
#################################################################
detailedResults: no

#################################################################
# Clear Existing Results - Clear results on server start?
# Syntax - ClearResultsFile [yes|no|ask]
#################################################################
clearResults: yes

#################################################################
# Resume Tournament - Resume tournament if results exist?
# Syntax - ClearResultsFile [yes|no|ask]
#################################################################
resumeTournament: no
